//视图类型枚举
public enum ViewType
{
    StartView,
    SetView,
    MessageView,
    LoadingView,
    SelectLevelView,
    FightView,
    FightSelectHeroView,
    DragHeroView,
    TipView,
    HeroDesView,
    EnemyDesView,
    SelectOptionView,
    FightOptionDesView,
    WinView,
    LossView
}
